[2024-08-12T00:53:51.371+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T00:53:51.375+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T00:53:51.375+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T00:53:51.381+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): test> on 2024-04-01 00:00:00+00:00
[2024-08-12T00:53:51.390+0000] {standard_task_runner.py:57} INFO - Started process 1380 to run task
[2024-08-12T00:53:51.393+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'test', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmprxdtgp4u']
[2024-08-12T00:53:51.394+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask test
[2024-08-12T00:53:51.428+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [running]> on host f7c751ddefa9
[2024-08-12T00:53:51.491+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T00:53:51.494+0000] {logging_mixin.py:151} INFO - tracking URI: 'http://mlflow:5000'
[2024-08-12T00:53:51.495+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T00:53:51.501+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=quarterly_retrain, task_id=test, execution_date=20240401T000000, start_date=20240812T005351, end_date=20240812T005351
[2024-08-12T00:53:51.535+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T00:53:51.544+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-12T03:40:11.029+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T03:40:11.033+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [queued]>
[2024-08-12T03:40:11.033+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T03:40:11.039+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): test> on 2024-04-01 00:00:00+00:00
[2024-08-12T03:40:11.043+0000] {standard_task_runner.py:57} INFO - Started process 5674 to run task
[2024-08-12T03:40:11.045+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'test', 'scheduled__2024-04-01T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmpo771ku3a']
[2024-08-12T03:40:11.046+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask test
[2024-08-12T03:40:11.077+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.test scheduled__2024-04-01T00:00:00+00:00 [running]> on host f7c751ddefa9
[2024-08-12T03:40:11.120+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='test' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-01T00:00:00+00:00'
[2024-08-12T03:40:11.122+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quarterly_retrain.py", line 174, in test
    df = pd.read_csv(path)
NameError: name 'pd' is not defined
[2024-08-12T03:40:11.128+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=quarterly_retrain, task_id=test, execution_date=20240401T000000, start_date=20240812T034011, end_date=20240812T034011
[2024-08-12T03:40:11.133+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task test (name 'pd' is not defined; 5674)
[2024-08-12T03:40:11.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T03:40:11.155+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
