[2024-08-12T03:35:31.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.load_transform_data manual__2024-08-12T03:35:29.655846+00:00 [queued]>
[2024-08-12T03:35:31.738+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.load_transform_data manual__2024-08-12T03:35:29.655846+00:00 [queued]>
[2024-08-12T03:35:31.739+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T03:35:31.743+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): load_transform_data> on 2024-08-12 03:35:29.655846+00:00
[2024-08-12T03:35:31.750+0000] {standard_task_runner.py:57} INFO - Started process 5066 to run task
[2024-08-12T03:35:31.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'load_transform_data', 'manual__2024-08-12T03:35:29.655846+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmpm7aj8ruy']
[2024-08-12T03:35:31.752+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask load_transform_data
[2024-08-12T03:35:31.777+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.load_transform_data manual__2024-08-12T03:35:29.655846+00:00 [running]> on host f7c751ddefa9
[2024-08-12T03:35:31.822+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='load_transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T03:35:29.655846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T03:35:29.655846+00:00'
[2024-08-12T03:35:32.466+0000] {python.py:194} INFO - Done. Returned value was: (           age  ...  payment_method_mailed_check
0     1.208536  ...                          0.0
1    -0.036557  ...                          0.0
2     0.912085  ...                          0.0
3     1.030665  ...                          0.0
4     0.734215  ...                          0.0
...        ...  ...                          ...
7565  0.522945  ...                          0.0
7566  1.515707  ...                          0.0
7567  0.330138  ...                          0.0
7568 -1.165819  ...                          0.0
7569  0.310816  ...                          0.0

[7570 rows x 56 columns],            age  ...  payment_method_mailed_check
0     0.518088  ...                          0.0
1     0.099498  ...                          0.0
2    -1.096473  ...                          0.0
3     1.116073  ...                          0.0
4     0.697483  ...                          0.0
...        ...  ...                          ...
1313 -0.259293  ...                          0.0
1314  1.534663  ...                          0.0
1315 -1.096473  ...                          0.0
1316  1.295469  ...                          0.0
1317  0.936677  ...                          0.0

[1318 rows x 56 columns], 0       0
1       0
2       0
3       0
4       0
       ..
7565    1
7566    1
7567    1
7568    1
7569    1
Name: customer_status, Length: 7570, dtype: int64, 2059    1
4323    0
1544    0
2644    0
4029    0
       ..
742     0
3275    0
3530    0
5587    0
716     0
Name: customer_status, Length: 1318, dtype: int64)
[2024-08-12T03:35:32.560+0000] {xcom.py:661} ERROR - Object of type tuple is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-08-12T03:35:32.561+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 145, in serialize
    return encode(classname, version, serialize(data, depth + 1))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 124, in serialize
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 124, in <listcomp>
    return [serialize(d, depth + 1) for d in o]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2477, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 102, in encode
    o = self.default(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tuple is not JSON serializable
[2024-08-12T03:35:32.568+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=quarterly_retrain, task_id=load_transform_data, execution_date=20240812T033529, start_date=20240812T033531, end_date=20240812T033532
[2024-08-12T03:35:32.574+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task load_transform_data (Object of type tuple is not JSON serializable; 5066)
[2024-08-12T03:35:32.618+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T03:35:32.630+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
