[2024-08-10T00:21:12.737+0000] {processor.py:157} INFO - Started process (PID=836) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:21:12.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:21:12.739+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:21:12.738+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:21:12.746+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:21:12.744+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:21:12.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:21:12.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T00:33:59.055+0000] {processor.py:157} INFO - Started process (PID=853) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:33:59.056+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:33:59.056+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:33:59.056+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:33:59.063+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:33:59.062+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:33:59.063+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:33:59.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.023 seconds
[2024-08-10T00:37:49.095+0000] {processor.py:157} INFO - Started process (PID=870) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:37:49.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:37:49.100+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:37:49.099+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:37:49.111+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:37:49.109+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:37:49.113+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:37:49.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.081 seconds
[2024-08-10T00:38:19.578+0000] {processor.py:157} INFO - Started process (PID=887) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:19.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:38:19.580+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:38:19.579+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:19.587+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:38:19.585+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:38:19.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:19.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.025 seconds
[2024-08-10T00:38:49.990+0000] {processor.py:157} INFO - Started process (PID=904) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:49.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:38:49.991+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:38:49.991+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:49.995+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:38:49.994+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:38:49.996+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:38:50.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T00:39:20.327+0000] {processor.py:157} INFO - Started process (PID=921) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:39:20.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:39:20.328+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:39:20.328+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:39:20.337+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:39:20.335+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:39:20.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:39:20.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.033 seconds
[2024-08-10T00:53:41.827+0000] {processor.py:157} INFO - Started process (PID=937) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:53:41.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T00:53:41.832+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:53:41.831+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:53:41.849+0000] {logging_mixin.py:151} INFO - [2024-08-10T00:53:41.845+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T00:53:41.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T00:53:41.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.106 seconds
[2024-08-10T01:01:03.388+0000] {processor.py:157} INFO - Started process (PID=957) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:01:03.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:01:03.390+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:01:03.390+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:01:03.399+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:01:03.397+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:01:03.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:01:03.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.043 seconds
[2024-08-10T01:15:11.386+0000] {processor.py:157} INFO - Started process (PID=973) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:15:11.388+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:15:11.390+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:15:11.389+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:15:11.403+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:15:11.401+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:15:11.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:15:11.458+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.088 seconds
[2024-08-10T01:19:44.155+0000] {processor.py:157} INFO - Started process (PID=990) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:19:44.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:19:44.158+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:19:44.158+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:19:44.168+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:19:44.167+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:19:44.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:19:44.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.063 seconds
[2024-08-10T01:20:20.141+0000] {processor.py:157} INFO - Started process (PID=1008) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:20.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:20:20.142+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:20:20.142+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:20.149+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:20:20.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:20:20.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:20.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T01:20:50.522+0000] {processor.py:157} INFO - Started process (PID=1025) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:50.524+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:20:50.525+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:20:50.524+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:50.534+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:20:50.533+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:20:50.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:20:50.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.051 seconds
[2024-08-10T01:21:20.999+0000] {processor.py:157} INFO - Started process (PID=1041) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:21.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:21:21.001+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:21:21.000+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:21.010+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:21:21.008+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:21:21.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:21.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.056 seconds
[2024-08-10T01:21:51.460+0000] {processor.py:157} INFO - Started process (PID=1058) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:51.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:21:51.463+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:21:51.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:51.472+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:21:51.471+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:21:51.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:21:51.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.065 seconds
[2024-08-10T01:22:21.860+0000] {processor.py:157} INFO - Started process (PID=1075) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:21.862+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:22:21.863+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:22:21.863+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:21.871+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:22:21.870+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:22:21.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:21.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.036 seconds
[2024-08-10T01:22:52.213+0000] {processor.py:157} INFO - Started process (PID=1092) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:52.215+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:22:52.216+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:22:52.215+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:52.228+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:22:52.226+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:22:52.229+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:22:52.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.041 seconds
[2024-08-10T01:23:22.532+0000] {processor.py:157} INFO - Started process (PID=1109) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:22.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:23:22.532+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:23:22.532+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:22.536+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:23:22.535+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:23:22.536+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:22.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T01:23:52.905+0000] {processor.py:157} INFO - Started process (PID=1126) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:52.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:23:52.905+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:23:52.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:52.909+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:23:52.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:23:52.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:23:52.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-10T01:24:23.258+0000] {processor.py:157} INFO - Started process (PID=1143) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:23.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:24:23.259+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:24:23.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:23.265+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:24:23.264+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:24:23.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:23.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T01:24:53.563+0000] {processor.py:157} INFO - Started process (PID=1160) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:53.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:24:53.565+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:24:53.564+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:53.568+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:24:53.568+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:24:53.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:24:53.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T01:31:18.474+0000] {processor.py:157} INFO - Started process (PID=1178) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:18.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:31:18.480+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:31:18.478+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:18.499+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:31:18.497+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:31:18.500+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:18.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.080 seconds
[2024-08-10T01:31:48.945+0000] {processor.py:157} INFO - Started process (PID=1196) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:48.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:31:48.946+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:31:48.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:48.952+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:31:48.951+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:31:48.953+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:31:48.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T01:32:19.367+0000] {processor.py:157} INFO - Started process (PID=1213) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:19.368+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:32:19.368+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:32:19.368+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:19.374+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:32:19.373+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:32:19.375+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:19.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T01:32:49.840+0000] {processor.py:157} INFO - Started process (PID=1229) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:49.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:32:49.841+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:32:49.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:49.846+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:32:49.845+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:32:49.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:32:49.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T01:33:53.978+0000] {processor.py:157} INFO - Started process (PID=1248) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:33:53.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:33:53.980+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:33:53.979+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:33:53.990+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:33:53.989+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:33:53.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:33:54.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.119 seconds
[2024-08-10T01:34:24.577+0000] {processor.py:157} INFO - Started process (PID=1264) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:34:24.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:34:24.581+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:34:24.580+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:34:24.593+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:34:24.591+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:34:24.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:34:24.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.072 seconds
[2024-08-10T01:44:37.550+0000] {processor.py:157} INFO - Started process (PID=1281) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:44:37.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:44:37.554+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:44:37.554+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:44:37.588+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:44:37.585+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:44:37.590+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:44:37.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.093 seconds
[2024-08-10T01:45:07.968+0000] {processor.py:157} INFO - Started process (PID=1299) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:07.969+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:45:07.969+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:45:07.969+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:07.974+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:45:07.973+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:45:07.974+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:07.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.023 seconds
[2024-08-10T01:45:38.310+0000] {processor.py:157} INFO - Started process (PID=1316) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:38.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:45:38.311+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:45:38.311+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:38.315+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:45:38.314+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:45:38.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:45:38.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-10T01:46:08.639+0000] {processor.py:157} INFO - Started process (PID=1333) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:08.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:46:08.640+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:46:08.640+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:08.646+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:46:08.645+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:46:08.647+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:08.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T01:46:38.957+0000] {processor.py:157} INFO - Started process (PID=1350) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:38.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:46:38.957+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:46:38.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:38.961+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:46:38.961+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:46:38.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:46:38.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T01:47:09.368+0000] {processor.py:157} INFO - Started process (PID=1367) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:09.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:47:09.369+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:47:09.369+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:09.376+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:47:09.375+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:47:09.377+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:09.391+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.025 seconds
[2024-08-10T01:47:39.794+0000] {processor.py:157} INFO - Started process (PID=1384) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:39.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:47:39.796+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:47:39.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:39.803+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:47:39.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:47:39.803+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:47:39.816+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T01:48:10.119+0000] {processor.py:157} INFO - Started process (PID=1401) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:10.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:48:10.120+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:48:10.120+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:10.124+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:48:10.123+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:48:10.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:10.134+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T01:48:40.459+0000] {processor.py:157} INFO - Started process (PID=1418) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:40.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:48:40.460+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:48:40.460+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:40.464+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:48:40.464+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:48:40.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:48:40.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T01:49:10.821+0000] {processor.py:157} INFO - Started process (PID=1435) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:10.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:49:10.822+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:49:10.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:10.828+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:49:10.827+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:49:10.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:10.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T01:49:41.000+0000] {processor.py:157} INFO - Started process (PID=1452) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:41.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:49:41.001+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:49:41.001+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:41.006+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:49:41.005+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:49:41.006+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:49:41.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T01:50:21.769+0000] {processor.py:157} INFO - Started process (PID=1469) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:50:21.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:50:21.772+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:50:21.771+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:50:21.790+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:50:21.786+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:50:21.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:50:21.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.053 seconds
[2024-08-10T01:51:19.894+0000] {processor.py:157} INFO - Started process (PID=1487) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:19.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:51:19.897+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:51:19.897+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:19.902+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:51:19.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:51:19.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:19.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T01:51:50.322+0000] {processor.py:157} INFO - Started process (PID=1504) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:50.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:51:50.323+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:51:50.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:50.346+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:51:50.345+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:51:50.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:51:50.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.048 seconds
[2024-08-10T01:53:56.899+0000] {processor.py:157} INFO - Started process (PID=1521) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:53:56.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:53:56.900+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:53:56.900+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:53:56.906+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:53:56.905+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:53:56.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:53:56.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T01:54:27.289+0000] {processor.py:157} INFO - Started process (PID=1538) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:27.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:54:27.291+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:54:27.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:27.312+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:54:27.311+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:54:27.312+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:27.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.039 seconds
[2024-08-10T01:54:57.704+0000] {processor.py:157} INFO - Started process (PID=1555) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:57.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:54:57.706+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:54:57.706+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:57.721+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:54:57.719+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:54:57.723+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:54:57.755+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.053 seconds
[2024-08-10T01:55:28.151+0000] {processor.py:157} INFO - Started process (PID=1572) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:28.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:55:28.152+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:55:28.152+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:28.158+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:55:28.157+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:55:28.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:28.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T01:55:58.796+0000] {processor.py:157} INFO - Started process (PID=1591) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:58.798+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:55:58.799+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:55:58.799+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:58.823+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:55:58.822+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:55:58.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:55:58.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.052 seconds
[2024-08-10T01:56:29.183+0000] {processor.py:157} INFO - Started process (PID=1608) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:29.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:56:29.186+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:56:29.185+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:29.211+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:56:29.210+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:56:29.211+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:29.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.049 seconds
[2024-08-10T01:56:59.573+0000] {processor.py:157} INFO - Started process (PID=1625) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:59.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:56:59.574+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:56:59.574+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:59.583+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:56:59.582+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:56:59.584+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:56:59.598+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-10T01:57:29.989+0000] {processor.py:157} INFO - Started process (PID=1647) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:57:29.991+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:57:29.992+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:57:29.991+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:57:30.000+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:57:29.999+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:57:30.000+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:57:30.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.046 seconds
[2024-08-10T01:58:00.334+0000] {processor.py:157} INFO - Started process (PID=1664) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:00.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:58:00.337+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:58:00.336+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:00.346+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:58:00.345+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:58:00.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:00.379+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.048 seconds
[2024-08-10T01:58:30.708+0000] {processor.py:157} INFO - Started process (PID=1686) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:30.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:58:30.710+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:58:30.710+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:30.721+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:58:30.719+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:58:30.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:58:30.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.054 seconds
[2024-08-10T01:59:01.063+0000] {processor.py:157} INFO - Started process (PID=1703) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:01.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:59:01.068+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:59:01.067+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:01.076+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:59:01.075+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:59:01.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:01.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.048 seconds
[2024-08-10T01:59:31.401+0000] {processor.py:157} INFO - Started process (PID=1720) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:31.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T01:59:31.404+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:59:31.403+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:31.412+0000] {logging_mixin.py:151} INFO - [2024-08-10T01:59:31.411+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T01:59:31.412+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T01:59:31.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.030 seconds
[2024-08-10T02:00:01.773+0000] {processor.py:157} INFO - Started process (PID=1737) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:01.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:00:01.777+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:00:01.776+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:01.795+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:00:01.794+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:00:01.796+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:01.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.043 seconds
[2024-08-10T02:00:32.145+0000] {processor.py:157} INFO - Started process (PID=1754) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:32.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:00:32.147+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:00:32.147+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:32.194+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:00:32.155+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:00:32.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:00:32.214+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.073 seconds
[2024-08-10T02:01:02.539+0000] {processor.py:157} INFO - Started process (PID=1771) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:02.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:01:02.542+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:01:02.542+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:02.551+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:01:02.549+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:01:02.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:02.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.032 seconds
[2024-08-10T02:01:32.873+0000] {processor.py:157} INFO - Started process (PID=1788) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:32.875+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:01:32.876+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:01:32.875+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:32.883+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:01:32.882+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:01:32.884+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:01:32.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.044 seconds
[2024-08-10T02:02:03.282+0000] {processor.py:157} INFO - Started process (PID=1805) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:03.284+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:02:03.285+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:02:03.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:03.293+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:02:03.292+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:02:03.294+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:03.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.040 seconds
[2024-08-10T02:02:33.626+0000] {processor.py:157} INFO - Started process (PID=1821) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:33.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:02:33.632+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:02:33.631+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:33.647+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:02:33.645+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:02:33.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:02:33.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.051 seconds
[2024-08-10T02:03:04.014+0000] {processor.py:157} INFO - Started process (PID=1838) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:04.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:03:04.017+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:03:04.016+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:04.024+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:03:04.023+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:03:04.024+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:04.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:03:34.328+0000] {processor.py:157} INFO - Started process (PID=1855) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:34.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:03:34.331+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:03:34.330+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:34.339+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:03:34.338+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:03:34.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:03:34.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.029 seconds
[2024-08-10T02:04:04.687+0000] {processor.py:157} INFO - Started process (PID=1872) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:04.688+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:04:04.693+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:04:04.691+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:04.712+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:04:04.710+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:04:04.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:04.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.061 seconds
[2024-08-10T02:04:35.090+0000] {processor.py:157} INFO - Started process (PID=1889) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:35.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:04:35.092+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:04:35.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:35.099+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:04:35.098+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:04:35.100+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:04:35.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-10T02:05:05.489+0000] {processor.py:157} INFO - Started process (PID=1906) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:05.492+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:05:05.501+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:05:05.499+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:05.519+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:05:05.518+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:05:05.520+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:05.536+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.050 seconds
[2024-08-10T02:05:35.872+0000] {processor.py:157} INFO - Started process (PID=1923) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:35.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:05:35.874+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:05:35.874+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:35.881+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:05:35.880+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:05:35.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:05:35.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:06:06.218+0000] {processor.py:157} INFO - Started process (PID=1940) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:06.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:06:06.220+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:06:06.220+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:06.224+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:06:06.224+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:06:06.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:06.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:06:36.580+0000] {processor.py:157} INFO - Started process (PID=1957) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:36.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:06:36.583+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:06:36.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:36.591+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:06:36.590+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:06:36.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:06:36.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.027 seconds
[2024-08-10T02:07:06.958+0000] {processor.py:157} INFO - Started process (PID=1974) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:06.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:07:06.960+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:07:06.960+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:06.968+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:07:06.967+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:07:06.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:06.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-10T02:07:37.272+0000] {processor.py:157} INFO - Started process (PID=1991) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:37.274+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:07:37.275+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:07:37.274+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:37.281+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:07:37.280+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:07:37.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:07:37.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:08:07.595+0000] {processor.py:157} INFO - Started process (PID=2008) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:07.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:08:07.597+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:08:07.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:07.601+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:08:07.600+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:08:07.601+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:07.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-10T02:08:37.987+0000] {processor.py:157} INFO - Started process (PID=2025) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:37.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:08:37.994+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:08:37.994+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:38.006+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:08:38.004+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:08:38.006+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:08:38.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.053 seconds
[2024-08-10T02:10:06.704+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:06.705+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:10:06.705+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:10:06.705+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:06.730+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:10:06.725+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:10:06.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:06.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.052 seconds
[2024-08-10T02:10:37.056+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:37.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:10:37.057+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:10:37.057+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:37.061+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:10:37.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:10:37.061+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:10:37.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T02:11:07.379+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:07.380+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:11:07.380+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:11:07.380+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:07.385+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:11:07.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:11:07.385+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:07.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-10T02:11:37.721+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:37.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:11:37.722+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:11:37.722+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:37.729+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:11:37.728+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:11:37.729+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:11:37.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T02:12:08.052+0000] {processor.py:157} INFO - Started process (PID=244) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:08.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:12:08.053+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:12:08.053+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:08.057+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:12:08.057+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:12:08.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:08.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-10T02:12:38.449+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:38.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:12:38.450+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:12:38.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:38.457+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:12:38.456+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:12:38.457+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:12:38.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.031 seconds
[2024-08-10T02:13:08.782+0000] {processor.py:157} INFO - Started process (PID=278) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:08.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:13:08.783+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:13:08.783+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:08.793+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:13:08.789+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:13:08.793+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:08.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:13:39.233+0000] {processor.py:157} INFO - Started process (PID=295) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:39.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:13:39.234+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:13:39.234+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:39.238+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:13:39.238+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:13:39.239+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:13:39.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T02:14:09.606+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:09.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:14:09.614+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:14:09.613+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:09.627+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:14:09.624+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:14:09.628+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:09.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.069 seconds
[2024-08-10T02:14:40.075+0000] {processor.py:157} INFO - Started process (PID=328) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:40.076+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:14:40.077+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:14:40.077+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:40.085+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:14:40.083+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:14:40.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:14:40.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.077 seconds
[2024-08-10T02:15:10.489+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:10.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:15:10.490+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:15:10.490+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:10.496+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:15:10.495+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:15:10.496+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:10.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.033 seconds
[2024-08-10T02:15:40.642+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:40.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:15:40.643+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:15:40.643+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:40.648+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:15:40.647+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:15:40.648+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:15:40.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.035 seconds
[2024-08-10T02:16:10.952+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:10.954+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:16:10.956+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:16:10.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:10.960+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:16:10.959+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:16:10.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:10.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.042 seconds
[2024-08-10T02:16:41.325+0000] {processor.py:157} INFO - Started process (PID=398) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:41.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:16:41.327+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:16:41.326+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:41.332+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:16:41.330+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:16:41.332+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:16:41.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.058 seconds
[2024-08-10T02:17:11.803+0000] {processor.py:157} INFO - Started process (PID=422) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:11.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:17:11.812+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:17:11.810+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:11.821+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:17:11.818+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:17:11.822+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:11.844+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.052 seconds
[2024-08-10T02:17:42.148+0000] {processor.py:157} INFO - Started process (PID=440) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:42.149+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:17:42.150+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:17:42.149+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:42.165+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:17:42.163+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:17:42.165+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:17:42.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.039 seconds
[2024-08-10T02:18:12.504+0000] {processor.py:157} INFO - Started process (PID=458) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:12.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:18:12.506+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:18:12.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:12.511+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:18:12.510+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:18:12.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:12.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.033 seconds
[2024-08-10T02:18:42.852+0000] {processor.py:157} INFO - Started process (PID=476) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:42.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:18:42.856+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:18:42.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:42.865+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:18:42.863+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:18:42.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:18:42.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.050 seconds
[2024-08-10T02:19:13.238+0000] {processor.py:157} INFO - Started process (PID=494) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:13.239+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:19:13.240+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:19:13.239+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:13.245+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:19:13.243+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:19:13.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:13.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.030 seconds
[2024-08-10T02:19:43.592+0000] {processor.py:157} INFO - Started process (PID=512) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:43.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:19:43.594+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:19:43.594+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:43.598+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:19:43.597+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:19:43.598+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:19:43.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.025 seconds
[2024-08-10T02:20:13.922+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:13.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:20:13.923+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:20:13.923+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:13.926+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:20:13.925+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:20:13.926+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:13.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-10T02:20:44.241+0000] {processor.py:157} INFO - Started process (PID=552) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:44.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:20:44.248+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:20:44.246+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:44.259+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:20:44.258+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:20:44.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:20:44.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.046 seconds
[2024-08-10T02:21:14.551+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:14.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:21:14.552+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:21:14.552+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:14.556+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:21:14.555+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:21:14.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:14.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-10T02:21:44.860+0000] {processor.py:157} INFO - Started process (PID=608) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:44.861+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:21:44.861+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:21:44.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:44.866+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:21:44.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:21:44.867+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:21:44.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-10T02:22:15.192+0000] {processor.py:157} INFO - Started process (PID=635) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:15.193+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:22:15.193+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:22:15.193+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:15.198+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:22:15.197+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:22:15.198+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:15.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.032 seconds
[2024-08-10T02:22:45.557+0000] {processor.py:157} INFO - Started process (PID=653) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:45.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:22:45.558+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:22:45.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:45.563+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:22:45.562+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:22:45.563+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:22:45.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-10T02:23:15.905+0000] {processor.py:157} INFO - Started process (PID=671) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:15.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:23:15.907+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:23:15.907+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:15.913+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:23:15.911+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:23:15.913+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:15.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.043 seconds
[2024-08-10T02:23:46.294+0000] {processor.py:157} INFO - Started process (PID=689) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:46.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:23:46.296+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:23:46.295+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:46.301+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:23:46.299+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:23:46.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:23:46.329+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.040 seconds
[2024-08-10T02:24:16.668+0000] {processor.py:157} INFO - Started process (PID=706) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:16.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:24:16.670+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:24:16.670+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:16.678+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:24:16.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:24:16.680+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:16.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.058 seconds
[2024-08-10T02:24:47.067+0000] {processor.py:157} INFO - Started process (PID=724) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:47.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:24:47.069+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:24:47.069+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:47.073+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:24:47.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:24:47.073+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:24:47.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:25:17.393+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:17.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:25:17.394+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:25:17.394+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:17.397+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:25:17.396+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:25:17.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:17.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-10T02:25:47.711+0000] {processor.py:157} INFO - Started process (PID=760) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:47.711+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:25:47.712+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:25:47.712+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:47.716+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:25:47.715+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:25:47.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:25:47.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-10T02:26:17.997+0000] {processor.py:157} INFO - Started process (PID=778) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:17.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:26:17.998+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:26:17.998+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:18.001+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:26:18.000+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:26:18.002+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:18.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-10T02:26:48.339+0000] {processor.py:157} INFO - Started process (PID=796) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:48.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:26:48.340+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:26:48.340+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:48.344+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:26:48.343+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:26:48.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:26:48.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T02:27:18.637+0000] {processor.py:157} INFO - Started process (PID=814) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:18.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:27:18.638+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:27:18.638+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:18.641+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:27:18.640+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:27:18.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:18.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-10T02:27:48.988+0000] {processor.py:157} INFO - Started process (PID=832) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:48.989+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:27:48.989+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:27:48.989+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:48.993+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:27:48.992+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:27:48.993+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:27:49.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T02:28:19.301+0000] {processor.py:157} INFO - Started process (PID=850) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:19.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:28:19.302+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:28:19.302+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:19.305+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:28:19.304+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:28:19.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:19.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-10T02:28:49.580+0000] {processor.py:157} INFO - Started process (PID=868) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:49.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:28:49.581+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:28:49.581+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:49.587+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:28:49.586+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:28:49.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:28:49.601+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T02:29:19.886+0000] {processor.py:157} INFO - Started process (PID=886) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:19.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:29:19.888+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:29:19.888+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:19.890+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:29:19.890+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:29:19.891+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:19.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-10T02:29:50.249+0000] {processor.py:157} INFO - Started process (PID=903) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:50.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:29:50.251+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:29:50.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:50.255+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:29:50.254+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:29:50.256+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:29:50.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-10T02:30:20.635+0000] {processor.py:157} INFO - Started process (PID=921) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:20.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:30:20.636+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:30:20.636+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:20.640+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:30:20.639+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:30:20.641+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:20.653+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T02:30:51.052+0000] {processor.py:157} INFO - Started process (PID=939) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:51.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:30:51.056+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:30:51.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:51.062+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:30:51.060+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:30:51.062+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:30:51.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.031 seconds
[2024-08-10T02:31:21.469+0000] {processor.py:157} INFO - Started process (PID=957) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:21.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:31:21.471+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:31:21.471+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:21.477+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:31:21.475+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:31:21.477+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:21.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.044 seconds
[2024-08-10T02:31:51.813+0000] {processor.py:157} INFO - Started process (PID=974) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:51.814+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:31:51.815+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:31:51.815+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:51.819+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:31:51.818+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:31:51.819+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:31:51.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T02:32:22.171+0000] {processor.py:157} INFO - Started process (PID=992) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:22.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:32:22.172+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:32:22.172+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:22.176+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:32:22.174+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:32:22.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:22.187+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:32:52.466+0000] {processor.py:157} INFO - Started process (PID=1010) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:52.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:32:52.468+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:32:52.467+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:52.471+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:32:52.470+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:32:52.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:32:52.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-10T02:33:22.777+0000] {processor.py:157} INFO - Started process (PID=1028) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:22.778+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:33:22.780+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:33:22.779+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:22.784+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:33:22.783+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:33:22.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:22.810+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.037 seconds
[2024-08-10T02:33:53.140+0000] {processor.py:157} INFO - Started process (PID=1045) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:53.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:33:53.141+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:33:53.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:53.145+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:33:53.144+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:33:53.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:33:53.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-10T02:34:23.497+0000] {processor.py:157} INFO - Started process (PID=1063) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:23.498+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:34:23.498+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:34:23.498+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:23.503+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:34:23.502+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:34:23.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:23.520+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.027 seconds
[2024-08-10T02:34:53.818+0000] {processor.py:157} INFO - Started process (PID=1081) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:53.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:34:53.823+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:34:53.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:53.828+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:34:53.826+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:34:53.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:34:53.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.047 seconds
[2024-08-10T02:35:24.211+0000] {processor.py:157} INFO - Started process (PID=1099) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:24.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:35:24.213+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:35:24.213+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:24.216+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:35:24.215+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:35:24.216+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:24.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:35:54.541+0000] {processor.py:157} INFO - Started process (PID=1117) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:54.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:35:54.543+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:35:54.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:54.546+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:35:54.545+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:35:54.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:35:54.557+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:36:24.861+0000] {processor.py:157} INFO - Started process (PID=1135) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:24.862+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:36:24.862+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:36:24.862+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:24.866+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:36:24.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:36:24.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:24.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:36:55.183+0000] {processor.py:157} INFO - Started process (PID=1153) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:55.184+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:36:55.185+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:36:55.184+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:55.188+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:36:55.187+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:36:55.188+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:36:55.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-10T02:37:25.589+0000] {processor.py:157} INFO - Started process (PID=1171) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:25.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:37:25.591+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:37:25.590+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:25.597+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:37:25.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:37:25.597+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:25.611+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.026 seconds
[2024-08-10T02:37:55.985+0000] {processor.py:157} INFO - Started process (PID=1188) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:55.986+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:37:55.987+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:37:55.986+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:55.991+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:37:55.990+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:37:55.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:37:56.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.023 seconds
[2024-08-10T02:38:26.347+0000] {processor.py:157} INFO - Started process (PID=1206) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:26.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:38:26.349+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:38:26.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:26.353+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:38:26.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:38:26.354+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:26.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.023 seconds
[2024-08-10T02:38:56.680+0000] {processor.py:157} INFO - Started process (PID=1223) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:56.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:38:56.681+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:38:56.681+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:56.684+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:38:56.683+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:38:56.685+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:38:56.696+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-10T02:39:27.033+0000] {processor.py:157} INFO - Started process (PID=1240) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:27.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:39:27.035+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:39:27.035+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:27.041+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:39:27.039+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:39:27.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:27.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.056 seconds
[2024-08-10T02:39:57.470+0000] {processor.py:157} INFO - Started process (PID=1257) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:57.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:39:57.478+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:39:57.477+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:57.513+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:39:57.508+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:39:57.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:39:57.593+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.129 seconds
[2024-08-10T02:40:27.958+0000] {processor.py:157} INFO - Started process (PID=1275) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:27.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:40:27.961+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:40:27.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:27.967+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:40:27.965+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:40:27.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:28.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.050 seconds
[2024-08-10T02:40:58.372+0000] {processor.py:157} INFO - Started process (PID=1292) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:58.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:40:58.376+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:40:58.375+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:58.387+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:40:58.384+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:40:58.387+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:40:58.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.057 seconds
[2024-08-10T02:41:28.854+0000] {processor.py:157} INFO - Started process (PID=1310) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:28.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:41:28.859+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:41:28.858+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:28.867+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:41:28.866+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:41:28.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:28.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.087 seconds
[2024-08-10T02:41:59.346+0000] {processor.py:157} INFO - Started process (PID=1328) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:59.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:41:59.347+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:41:59.347+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:59.353+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:41:59.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:41:59.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:41:59.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.043 seconds
[2024-08-10T02:42:29.741+0000] {processor.py:157} INFO - Started process (PID=1346) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:42:29.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:42:29.743+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:42:29.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:42:29.746+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:42:29.745+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:42:29.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:42:29.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.022 seconds
[2024-08-10T02:43:00.046+0000] {processor.py:157} INFO - Started process (PID=1364) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:00.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:43:00.047+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:43:00.047+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:00.051+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:43:00.050+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:43:00.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:00.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.023 seconds
[2024-08-10T02:43:30.413+0000] {processor.py:157} INFO - Started process (PID=1382) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:30.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:43:30.415+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:43:30.414+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:30.420+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:43:30.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:43:30.421+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:43:30.438+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.029 seconds
[2024-08-10T02:44:00.770+0000] {processor.py:157} INFO - Started process (PID=1400) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:00.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:44:00.772+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:44:00.771+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:00.778+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:44:00.776+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:44:00.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:00.814+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.050 seconds
[2024-08-10T02:44:31.062+0000] {processor.py:157} INFO - Started process (PID=1417) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:31.063+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-10T02:44:31.064+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:44:31.064+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:31.067+0000] {logging_mixin.py:151} INFO - [2024-08-10T02:44:31.067+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-10T02:44:31.068+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-10T02:44:31.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
