[2024-08-12T17:15:43.251+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_prediction.predict_and_save manual__2024-08-12T17:15:39.019866+00:00 [queued]>
[2024-08-12T17:15:43.254+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_prediction.predict_and_save manual__2024-08-12T17:15:39.019866+00:00 [queued]>
[2024-08-12T17:15:43.254+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T17:15:43.259+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): predict_and_save> on 2024-08-12 17:15:39.019866+00:00
[2024-08-12T17:15:43.263+0000] {standard_task_runner.py:57} INFO - Started process 757 to run task
[2024-08-12T17:15:43.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_prediction', 'predict_and_save', 'manual__2024-08-12T17:15:39.019866+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/monthly_prediction.py', '--cfg-path', '/tmp/tmphd9kew3i']
[2024-08-12T17:15:43.266+0000] {standard_task_runner.py:85} INFO - Job 181: Subtask predict_and_save
[2024-08-12T17:15:43.288+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_prediction.predict_and_save manual__2024-08-12T17:15:39.019866+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T17:15:43.447+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_prediction' AIRFLOW_CTX_TASK_ID='predict_and_save' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T17:15:39.019866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T17:15:39.019866+00:00'
[2024-08-12T17:15:43.752+0000] {logging_mixin.py:151} INFO - []
[2024-08-12T17:15:43.752+0000] {logging_mixin.py:151} INFO - no registered model found
[2024-08-12T17:15:43.761+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monthly_prediction.py", line 49, in predict_and_save
    prediction = model.predict(df_transformed)
AttributeError: 'NoneType' object has no attribute 'predict'
[2024-08-12T17:15:43.768+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_prediction, task_id=predict_and_save, execution_date=20240812T171539, start_date=20240812T171543, end_date=20240812T171543
[2024-08-12T17:15:43.852+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 181 for task predict_and_save ('NoneType' object has no attribute 'predict'; 757)
[2024-08-12T17:15:43.911+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T17:15:43.924+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
