[2024-08-12T04:21:10.588+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:21:04.940598+00:00 [queued]>
[2024-08-12T04:21:10.591+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:21:04.940598+00:00 [queued]>
[2024-08-12T04:21:10.591+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T04:21:10.596+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): run_models> on 2024-08-12 04:21:04.940598+00:00
[2024-08-12T04:21:10.600+0000] {standard_task_runner.py:57} INFO - Started process 9490 to run task
[2024-08-12T04:21:10.602+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'run_models', 'manual__2024-08-12T04:21:04.940598+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmpgfdlc2o3']
[2024-08-12T04:21:10.602+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask run_models
[2024-08-12T04:21:10.636+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:21:04.940598+00:00 [running]> on host f7c751ddefa9
[2024-08-12T04:21:12.612+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='run_models' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T04:21:04.940598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T04:21:04.940598+00:00'
[2024-08-12T04:21:12.702+0000] {logging_mixin.py:151} WARNING - 2024/08/12 04:21:12 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-08-12T04:21:12.743+0000] {logging_mixin.py:151} INFO - training LogisticRegression
[2024-08-12T04:21:15.603+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-08-12T04:21:15.638+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quarterly_retrain.py", line 146, in run_models
    run_model(LogisticRegression(), X_train, X_val, y_train, y_val)
  File "/opt/airflow/dags/quarterly_retrain.py", line 31, in run_model
    mlflow.sklearn.log_model(model, artifact_path='models')
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 412, in log_model
    return Model.log(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/models/model.py", line 696, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1106, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1926, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 846, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 66, in log_artifacts
    mkdir(artifact_dir)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 211, in mkdir
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 208, in mkdir
    os.makedirs(target, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mlflow'
[2024-08-12T04:21:15.648+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=quarterly_retrain, task_id=run_models, execution_date=20240812T042104, start_date=20240812T042110, end_date=20240812T042115
[2024-08-12T04:21:15.655+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task run_models ([Errno 13] Permission denied: '/mlflow'; 9490)
[2024-08-12T04:21:15.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T04:21:15.685+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
