[2024-08-12T04:52:22.610+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:52:16.498290+00:00 [queued]>
[2024-08-12T04:52:22.614+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:52:16.498290+00:00 [queued]>
[2024-08-12T04:52:22.614+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T04:52:22.620+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): run_models> on 2024-08-12 04:52:16.498290+00:00
[2024-08-12T04:52:22.624+0000] {standard_task_runner.py:57} INFO - Started process 542 to run task
[2024-08-12T04:52:22.626+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'run_models', 'manual__2024-08-12T04:52:16.498290+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmpvg9o6pnj']
[2024-08-12T04:52:22.627+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask run_models
[2024-08-12T04:52:22.654+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.run_models manual__2024-08-12T04:52:16.498290+00:00 [running]> on host fa284eed0508
[2024-08-12T04:52:25.724+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='run_models' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T04:52:16.498290+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T04:52:16.498290+00:00'
[2024-08-12T04:52:25.799+0000] {logging_mixin.py:151} WARNING - 2024/08/12 04:52:25 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-08-12T04:52:25.829+0000] {logging_mixin.py:151} INFO - training LogisticRegression
[2024-08-12T04:52:28.800+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-08-12T04:52:29.880+0000] {logging_mixin.py:151} INFO - training RandomForestClassifier
[2024-08-12T04:52:33.572+0000] {logging_mixin.py:151} INFO - training XGBClassifier
[2024-08-12T04:52:37.475+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T04:52:37.487+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=quarterly_retrain, task_id=run_models, execution_date=20240812T045216, start_date=20240812T045222, end_date=20240812T045237
[2024-08-12T04:52:37.520+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T04:52:37.532+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
