[2024-08-12T18:04:47.869+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.prep_data scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-08-12T18:04:47.907+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.prep_data scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-08-12T18:04:47.935+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:04:47.990+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): prep_data> on 2024-02-01 00:00:00+00:00
[2024-08-12T18:04:48.067+0000] {standard_task_runner.py:57} INFO - Started process 7840 to run task
[2024-08-12T18:04:48.072+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'prep_data', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmpix8eenl2']
[2024-08-12T18:04:48.094+0000] {standard_task_runner.py:85} INFO - Job 207: Subtask prep_data
[2024-08-12T18:04:48.341+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.prep_data scheduled__2024-02-01T00:00:00+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:04:48.872+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='prep_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-08-12T18:04:48.894+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 65, in prep_data
    previous_month = (month_end + pd.offsets.MonthEnd(-1))
TypeError: can only concatenate str (not "pandas._libs.tslibs.offsets.MonthEnd") to str
[2024-08-12T18:04:49.007+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=prep_data, execution_date=20240201T000000, start_date=20240812T180447, end_date=20240812T180448
[2024-08-12T18:04:49.076+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 207 for task prep_data (can only concatenate str (not "pandas._libs.tslibs.offsets.MonthEnd") to str; 7840)
[2024-08-12T18:04:49.172+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T18:04:49.361+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
