[2024-08-09T18:36:20.261+0000] {processor.py:157} INFO - Started process (PID=176) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:20.265+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:36:20.266+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:36:20.266+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:20.290+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:36:20.287+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:36:20.290+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:20.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.045 seconds
[2024-08-09T18:36:50.558+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:50.559+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:36:50.560+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:36:50.560+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:50.577+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:36:50.570+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:36:50.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:36:50.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.090 seconds
[2024-08-09T18:37:20.961+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:20.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:37:20.963+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:37:20.962+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:20.969+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:37:20.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:37:20.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:20.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.032 seconds
[2024-08-09T18:37:51.328+0000] {processor.py:157} INFO - Started process (PID=226) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:51.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:37:51.329+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:37:51.328+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:51.335+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:37:51.334+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:37:51.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:37:51.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-09T18:38:21.699+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:21.699+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:38:21.700+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:38:21.700+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:21.705+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:38:21.704+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:38:21.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:21.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-09T18:38:52.026+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:52.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:38:52.027+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:38:52.027+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:52.034+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:38:52.033+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:38:52.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:38:52.048+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.024 seconds
[2024-08-09T18:39:22.362+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:22.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:39:22.363+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:39:22.362+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:22.366+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:39:22.365+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:39:22.366+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:22.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-09T18:39:52.734+0000] {processor.py:157} INFO - Started process (PID=293) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:52.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:39:52.738+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:39:52.738+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:52.742+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:39:52.741+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:39:52.743+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:39:52.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.020 seconds
[2024-08-09T18:40:23.047+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:23.047+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:40:23.048+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:40:23.048+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:23.053+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:40:23.052+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:40:23.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:23.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.019 seconds
[2024-08-09T18:40:53.388+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:53.389+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:40:53.390+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:40:53.390+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:53.398+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:40:53.397+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:40:53.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:40:53.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.041 seconds
[2024-08-09T18:41:23.798+0000] {processor.py:157} INFO - Started process (PID=342) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:41:23.799+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:41:23.799+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:41:23.799+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:41:23.806+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:41:23.805+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:41:23.806+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:41:23.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.021 seconds
[2024-08-09T18:57:10.523+0000] {processor.py:157} INFO - Started process (PID=349) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:57:10.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T18:57:10.524+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:57:10.523+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:57:10.528+0000] {logging_mixin.py:151} INFO - [2024-08-09T18:57:10.527+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T18:57:10.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T18:57:10.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-09T19:12:05.946+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:05.947+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:12:05.948+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:12:05.948+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:05.971+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:12:05.961+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:12:05.973+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:06.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.073 seconds
[2024-08-09T19:12:36.420+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:36.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:12:36.421+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:12:36.420+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:36.424+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:12:36.424+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:12:36.425+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:12:36.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.018 seconds
[2024-08-09T19:13:06.843+0000] {processor.py:157} INFO - Started process (PID=401) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:06.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:13:06.847+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:13:06.847+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:06.862+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:13:06.860+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:13:06.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:06.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.048 seconds
[2024-08-09T19:13:37.288+0000] {processor.py:157} INFO - Started process (PID=419) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:37.289+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:13:37.289+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:13:37.289+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:37.295+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:13:37.294+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:13:37.296+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:13:37.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.028 seconds
[2024-08-09T19:25:23.128+0000] {processor.py:157} INFO - Started process (PID=438) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:25:23.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:25:23.131+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:25:23.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:25:23.147+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:25:23.144+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:25:23.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:25:23.228+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.108 seconds
[2024-08-09T19:43:09.610+0000] {processor.py:157} INFO - Started process (PID=454) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:43:09.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:43:09.618+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:43:09.617+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:43:09.633+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:43:09.630+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:43:09.633+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:43:09.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.072 seconds
[2024-08-09T19:53:05.960+0000] {processor.py:157} INFO - Started process (PID=472) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:53:05.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:53:05.962+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:53:05.962+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:53:05.976+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:53:05.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:53:05.978+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:53:06.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.070 seconds
[2024-08-09T19:56:15.710+0000] {processor.py:157} INFO - Started process (PID=491) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:56:15.712+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T19:56:15.713+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:56:15.713+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:56:15.722+0000] {logging_mixin.py:151} INFO - [2024-08-09T19:56:15.721+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T19:56:15.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T19:56:15.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.045 seconds
[2024-08-09T20:00:58.556+0000] {processor.py:157} INFO - Started process (PID=507) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:00:58.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:00:58.562+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:00:58.561+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:00:58.581+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:00:58.577+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:00:58.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:00:58.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.090 seconds
[2024-08-09T20:01:29.015+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:29.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:01:29.018+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:01:29.017+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:29.044+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:01:29.040+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:01:29.044+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:29.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.050 seconds
[2024-08-09T20:01:59.451+0000] {processor.py:157} INFO - Started process (PID=542) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:59.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:01:59.453+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:01:59.453+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:59.462+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:01:59.460+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:01:59.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:01:59.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.046 seconds
[2024-08-09T20:02:29.904+0000] {processor.py:157} INFO - Started process (PID=559) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:02:29.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:02:29.905+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:02:29.905+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:02:29.909+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:02:29.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:02:29.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:02:29.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.016 seconds
[2024-08-09T20:05:37.656+0000] {processor.py:157} INFO - Started process (PID=575) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:05:37.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:05:37.659+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:05:37.658+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:05:37.679+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:05:37.673+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:05:37.682+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:05:37.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.057 seconds
[2024-08-09T20:24:33.814+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:24:33.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:24:33.816+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:24:33.815+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:24:33.823+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:24:33.822+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:24:33.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:24:33.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.029 seconds
[2024-08-09T20:38:24.897+0000] {processor.py:157} INFO - Started process (PID=609) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:24.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:38:24.903+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:38:24.902+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:24.927+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:38:24.924+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:38:24.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:24.975+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.088 seconds
[2024-08-09T20:38:55.320+0000] {processor.py:157} INFO - Started process (PID=627) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:55.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:38:55.322+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:38:55.322+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:55.329+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:38:55.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:38:55.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:38:55.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.039 seconds
[2024-08-09T20:39:25.789+0000] {processor.py:157} INFO - Started process (PID=644) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:25.790+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:39:25.790+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:39:25.790+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:25.799+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:39:25.798+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:39:25.799+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:25.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.031 seconds
[2024-08-09T20:39:56.194+0000] {processor.py:157} INFO - Started process (PID=661) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:56.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:39:56.195+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:39:56.195+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:56.199+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:39:56.199+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:39:56.199+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:39:56.210+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.017 seconds
[2024-08-09T20:50:03.404+0000] {processor.py:157} INFO - Started process (PID=678) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:50:03.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T20:50:03.418+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:50:03.418+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:50:03.478+0000] {logging_mixin.py:151} INFO - [2024-08-09T20:50:03.456+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T20:50:03.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T20:50:03.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.179 seconds
[2024-08-09T21:14:17.486+0000] {processor.py:157} INFO - Started process (PID=696) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:14:17.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T21:14:17.488+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:14:17.488+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:14:17.495+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:14:17.493+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T21:14:17.495+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:14:17.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.029 seconds
[2024-08-09T21:15:06.368+0000] {processor.py:157} INFO - Started process (PID=715) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:06.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T21:15:06.370+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:15:06.370+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:06.377+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:15:06.376+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T21:15:06.377+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:06.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.025 seconds
[2024-08-09T21:15:36.805+0000] {processor.py:157} INFO - Started process (PID=732) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:36.806+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T21:15:36.807+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:15:36.807+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:36.814+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:15:36.812+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T21:15:36.814+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:15:36.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.040 seconds
[2024-08-09T21:16:07.204+0000] {processor.py:157} INFO - Started process (PID=749) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:07.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T21:16:07.205+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:16:07.205+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:07.212+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:16:07.211+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T21:16:07.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:07.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.032 seconds
[2024-08-09T21:16:37.584+0000] {processor.py:157} INFO - Started process (PID=766) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:37.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T21:16:37.587+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:16:37.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:37.594+0000] {logging_mixin.py:151} INFO - [2024-08-09T21:16:37.592+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T21:16:37.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T21:16:37.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.038 seconds
[2024-08-09T22:12:29.439+0000] {processor.py:157} INFO - Started process (PID=785) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:12:29.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T22:12:29.444+0000] {logging_mixin.py:151} INFO - [2024-08-09T22:12:29.443+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:12:29.457+0000] {logging_mixin.py:151} INFO - [2024-08-09T22:12:29.454+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T22:12:29.457+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:12:29.495+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.061 seconds
[2024-08-09T22:56:57.189+0000] {processor.py:157} INFO - Started process (PID=801) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:56:57.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T22:56:57.191+0000] {logging_mixin.py:151} INFO - [2024-08-09T22:56:57.191+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:56:57.199+0000] {logging_mixin.py:151} INFO - [2024-08-09T22:56:57.198+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T22:56:57.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T22:56:57.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.030 seconds
[2024-08-09T23:28:06.201+0000] {processor.py:157} INFO - Started process (PID=818) to work on /opt/airflow/dags/annual_retrain.py
[2024-08-09T23:28:06.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/annual_retrain.py for tasks to queue
[2024-08-09T23:28:06.203+0000] {logging_mixin.py:151} INFO - [2024-08-09T23:28:06.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/annual_retrain.py
[2024-08-09T23:28:06.213+0000] {logging_mixin.py:151} INFO - [2024-08-09T23:28:06.211+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/annual_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/annual_retrain.py", line 7, in <module>
    'start_date': datetime(2023, 1, 1),
NameError: name 'datetime' is not defined
[2024-08-09T23:28:06.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/annual_retrain.py
[2024-08-09T23:28:06.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/annual_retrain.py took 0.032 seconds
