[2024-08-12T03:59:59.009+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T03:59:53.806924+00:00 [queued]>
[2024-08-12T03:59:59.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T03:59:53.806924+00:00 [queued]>
[2024-08-12T03:59:59.013+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T03:59:59.018+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): run_models> on 2024-08-12 03:59:53.806924+00:00
[2024-08-12T03:59:59.023+0000] {standard_task_runner.py:57} INFO - Started process 7648 to run task
[2024-08-12T03:59:59.025+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'run_models', 'manual__2024-08-12T03:59:53.806924+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmp8wd1i7tg']
[2024-08-12T03:59:59.026+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask run_models
[2024-08-12T03:59:59.050+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.run_models manual__2024-08-12T03:59:53.806924+00:00 [running]> on host f7c751ddefa9
[2024-08-12T03:59:59.082+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'run_models', field 'op_args'. Template: (XComArg(<Task(_PythonDecoratedOperator): load_transform_data>, 'X_train'), XComArg(<Task(_PythonDecoratedOperator): load_transform_data>, 'X_val'), XComArg(<Task(_PythonDecoratedOperator): load_transform_data>, 'y_train'), XComArg(<Task(_PythonDecoratedOperator): load_transform_data>, 'y_val'))
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 163, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 163, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 159, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 433, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from load_transform_data at quarterly_retrain with key="X_train" is not found!
[2024-08-12T03:59:59.088+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1645, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2283, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1245, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 163, in render_template
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 163, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env, oids) for element in value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 159, in render_template
    return value.resolve(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 433, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from load_transform_data at quarterly_retrain with key="X_train" is not found!
[2024-08-12T03:59:59.092+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=quarterly_retrain, task_id=run_models, execution_date=20240812T035953, start_date=20240812T035959, end_date=20240812T035959
[2024-08-12T03:59:59.098+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task run_models (XComArg result from load_transform_data at quarterly_retrain with key="X_train" is not found!; 7648)
[2024-08-12T03:59:59.123+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T03:59:59.136+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
