[2024-08-12T17:16:40.309+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T17:16:34.875723+00:00 [queued]>
[2024-08-12T17:16:40.313+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarterly_retrain.run_models manual__2024-08-12T17:16:34.875723+00:00 [queued]>
[2024-08-12T17:16:40.314+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T17:16:40.320+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): run_models> on 2024-08-12 17:16:34.875723+00:00
[2024-08-12T17:16:40.324+0000] {standard_task_runner.py:57} INFO - Started process 916 to run task
[2024-08-12T17:16:40.326+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'quarterly_retrain', 'run_models', 'manual__2024-08-12T17:16:34.875723+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/quarterly_retrain.py', '--cfg-path', '/tmp/tmps6ofbjr0']
[2024-08-12T17:16:40.326+0000] {standard_task_runner.py:85} INFO - Job 183: Subtask run_models
[2024-08-12T17:16:40.353+0000] {task_command.py:415} INFO - Running <TaskInstance: quarterly_retrain.run_models manual__2024-08-12T17:16:34.875723+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T17:16:43.209+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarterly_retrain' AIRFLOW_CTX_TASK_ID='run_models' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T17:16:34.875723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T17:16:34.875723+00:00'
[2024-08-12T17:16:43.306+0000] {logging_mixin.py:151} WARNING - 2024/08/12 17:16:43 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-08-12T17:16:43.359+0000] {logging_mixin.py:151} INFO - training LogisticRegression
[2024-08-12T17:16:46.835+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-08-12T17:16:48.180+0000] {logging_mixin.py:151} INFO - training RandomForestClassifier
[2024-08-12T17:16:52.134+0000] {logging_mixin.py:151} INFO - training XGBClassifier
[2024-08-12T17:16:56.212+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-08-12T17:16:56.241+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=quarterly_retrain, task_id=run_models, execution_date=20240812T171634, start_date=20240812T171640, end_date=20240812T171656
[2024-08-12T17:16:56.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-12T17:16:56.282+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
