[2024-08-12T18:07:31.334+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_monitor.prep_data manual__2024-08-12T18:07:28.194931+00:00 [queued]>
[2024-08-12T18:07:31.351+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_monitor.prep_data manual__2024-08-12T18:07:28.194931+00:00 [queued]>
[2024-08-12T18:07:31.351+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-08-12T18:07:31.363+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): prep_data> on 2024-08-12 18:07:28.194931+00:00
[2024-08-12T18:07:31.371+0000] {standard_task_runner.py:57} INFO - Started process 8218 to run task
[2024-08-12T18:07:31.376+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'monthly_monitor', 'prep_data', 'manual__2024-08-12T18:07:28.194931+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/monitor.py', '--cfg-path', '/tmp/tmp6p6grxaw']
[2024-08-12T18:07:31.379+0000] {standard_task_runner.py:85} INFO - Job 226: Subtask prep_data
[2024-08-12T18:07:31.532+0000] {task_command.py:415} INFO - Running <TaskInstance: monthly_monitor.prep_data manual__2024-08-12T18:07:28.194931+00:00 [running]> on host a9166c5dc5ae
[2024-08-12T18:07:31.604+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_monitor' AIRFLOW_CTX_TASK_ID='prep_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-12T18:07:28.194931+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-12T18:07:28.194931+00:00'
[2024-08-12T18:07:31.608+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitor.py", line 65, in prep_data
    previous_month = (month_end + pd.offsets.MonthEnd(-1))
TypeError: can only concatenate str (not "pandas._libs.tslibs.offsets.MonthEnd") to str
[2024-08-12T18:07:31.623+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=monthly_monitor, task_id=prep_data, execution_date=20240812T180728, start_date=20240812T180731, end_date=20240812T180731
[2024-08-12T18:07:31.635+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 226 for task prep_data (can only concatenate str (not "pandas._libs.tslibs.offsets.MonthEnd") to str; 8218)
[2024-08-12T18:07:31.689+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-08-12T18:07:31.718+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
